### ISSUE TITLE
Unify language on profile page (review vs validate)

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/sentence-collector#124] opened 2019-01-18 13:02 UTC
In the profile page we are using validated and reviewed for the same purpose, we should unify language.

I suggest we use review, since we use validated in the home page for sentences with enough positive reviews.

Users don't validate, it's the combination of their review what constitutes a validation.

**Comment by MichaelKohler** [comment] 2019-01-18 13:11
With my additional comment in #88, is that now a dupe of that one?

**Closed** 2019-01-18 13:39 UTC
