### ISSUE TITLE
Added sentences are not the same as reviewed sentences

### ISSUE THREAD

**Issue by danielsjf** [Common-Voice/sentence-collector#75] opened 2019-01-08 13:51 UTC
Could it be that the ending apostrophe is messing with the sentence splitting? The first and the second sentence are mixed in the review phase. The apostrophe can be used in this way in Dutch (same as in English). It doesn't have this behavior for an apostrophe in the middle of a sentence as shown in the third sentence.

![screenshot_20190108-143721__01](https://user-images.githubusercontent.com/6696142/50834514-79040d00-1354-11e9-8309-64efa0054a29.jpg)
![screenshot_20190108-143731__01](https://user-images.githubusercontent.com/6696142/50834515-799ca380-1354-11e9-89d2-0f8a25d85e67.jpg)

**Comment by MichaelKohler** [comment] 2019-01-08 14:19
Good catch, thanks for testing and reporting. This indeed looks like a bug, can't say right now what exactly happens there though.

**Comment by MichaelKohler** [comment] 2019-01-08 21:59
I have tried to reproduce this, I unfortunately can't. Neither locally nor on the testing website. Can you try to reproduce this? (I have sucessfully submitted your sentences, so you will need to find new ones in the same style)

<img width="1410" alt="screenshot 2019-01-08 at 22 56 49" src="https://user-images.githubusercontent.com/330324/50861422-4af8ea00-13a1-11e9-9977-8c3113a06b8d.png">

Review before submitting:
<img width="1412" alt="screenshot 2019-01-08 at 22 57 02" src="https://user-images.githubusercontent.com/330324/50861435-577d4280-13a1-11e9-8fbe-b572765dd3dd.png">

Review after submitting:
<img width="1418" alt="screenshot 2019-01-08 at 22 57 29" src="https://user-images.githubusercontent.com/330324/50861445-606e1400-13a1-11e9-9310-7b6f4ebd45c8.png">


Could be that the latest deployment including a new splitting mechanism has fixed this.

**Comment by danielsjf** [comment] 2019-01-08 23:43
Strange. It also doesn't happen again for me, even with different sentences. Could it be that another fix fixed it? Yesterday it happened twice (once to see and once to reproduce).

**Comment by MichaelKohler** [comment] 2019-01-09 10:04
I'll check locally with an older version to make sure that this is indeed fixed with the latest change to the sentence splitting.

**Comment by MichaelKohler** [comment] 2019-01-09 17:35
I can confirm this is indeed fixed by the splitting algorithm change. It fails on an older version just as you reported. Great!

**Closed by MichaelKohler** 2019-01-09 17:35 UTC
Labels: frontend
