### ISSUE TITLE
Why would I need to login to view the statistics?

### ISSUE THREAD

**Issue by fnielsen** [common-voice/sentence-collector#444] opened 2021-05-26 23:03 UTC
Why would I need to login to view the statistics? I suppose some statistics is bound to language and language is bound to user. But I do not see why this restriction should be there.

**Comment by MichaelKohler** [comment] 2021-05-27 18:52
Exactly what you said, for now. Closing as duplicate of #149 . Thanks!

**Closed by MichaelKohler** 2021-05-27 18:52 UTC
