### ISSUE TITLE
Jump in review page after button press

### ISSUE THREAD

**Issue by robovoice1** [common-voice/sentence-collector#571] opened 2021-12-13 06:51 UTC
I started a review process in sentence collector, english language. I positioned the screen to my needs (see pic1).
 
![Screenshot_20211213-070559](https://user-images.githubusercontent.com/92784377/145764981-3e4cfd67-f223-409a-b84a-0cedd3732572.png)

After reviewing (100+) sentences within the review process the page "jumps down" (see pic2).
![Screenshot_20211213-071327](https://user-images.githubusercontent.com/92784377/145765039-74881fa2-07a2-4e12-af91-06742ef7696d.png)

The buttons (reject,.skip, approve) are not reachable anymore, and the contributor must move the page up again.
(possible accidental left/right swipes within the text box included)

A fixed position when in review process or place the text box as high as possible to the top of the review page could improve this for smartphone reviewers for reviewing many sentences. Place the explaining text under the box???

Os: Android10
Browser: Fx mobile  95.1.0 (Build #2015848803)
AC: 95.0.13, 58539f17f6
GV: 95.0-20211129150630
AS: 86.0.1
Hardware: Fairphone 3 plus used

**Comment by MichaelKohler** [comment] 2021-12-26 17:53
I started to look into this. This seems to happen when a review is submitted. I would argue that this per se is not a bug, as it's good that the user sees that happening.

However, as in your case most likely, there were more sentences added during your review session, and then got loaded, so it seemed like a bug. I'm keeping this open if anyone has a better idea on how to improve UX here (I don't think we should move the explanation below the whole card/buttons, we need to find another fix for this).

**Comment by robovoice1** [comment] 2021-12-31 17:03
OK, it was just a quick proposal with the text.

**Comment by robovoice1** [comment] 2022-01-01 12:20
Please watch screenrecording.
I submitted today about 100 german sentences, after almost every 2-3 sentences in review the page jumps down.

https://user-images.githubusercontent.com/92784377/147850423-d6e6b80a-da71-45fe-85dc-17df70294d63.mp4

**Comment by MichaelKohler** [comment] 2022-01-12 17:47
So far I wasn't able to reproduce this. I will keep having a look though.

**Comment by robovoice1** [comment] 2022-01-23 12:25
With Pixel 4a phone and Android 12/grapheneOS no jumping down at all!

**Comment by MichaelKohler** [comment] 2022-01-23 12:26
Is that because the screen resolution is higher and therefore the content fits anyway?

**Comment by robovoice1** [comment] 2022-01-23 12:30
Good point. Fairphone 3 itself is bigger, but pixel 4a has bigger screen resolution (more is displayed!)

**Comment by MichaelKohler** [comment] 2022-02-12 11:05
I would love some help here if somebody can figure out what exactly is going wrong here :)

**Comment by robovoice1** [comment] 2022-02-12 12:07
Maybe with this:
https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode

**Comment by MichaelKohler** [comment] 2022-02-12 12:55
My comment was meant for figuring out what in the code actually creates this issue. But yes, that indeed is the way to go to reproduce this.

**Comment by MichaelKohler** [comment] 2023-05-10 20:56
Thanks for bringing this up. The Sentence Collector now has moved to https://commonvoice.mozilla.org/write and therefore is now hosted in the main Common Voice repository. That being said, this issue is no longer relevant as that part of the review process has been changed.

**Closed by MichaelKohler** 2023-05-10 20:56 UTC
Labels: bug, help wanted, frontend, area: review, P2
