### ISSUE TITLE
sentences with enough vote not been exported

### ISSUE THREAD

**Issue by irvin** [Common-Voice/sentence-collector#245] opened 2019-07-30 15:45 UTC
It’s weird that we had add something like 4K zh-tw sentences to collector and make it review with multiple accounts, but so far we only have 1K validated and exported.

<img width="373" alt="螢幕快照 2019-07-30 下午11 37 08 1" src="https://user-images.githubusercontent.com/165936/62144180-efce1b00-b323-11e9-9265-c30527fd3962.png">

**Comment by MichaelKohler** [comment] 2019-07-30 17:32
I have looked into this the past days, for now I know the following:

1) there indeed are many records that should be approved, but the flag is not set
2) he records get updated with the username of the reviewer, so it's not a pure network error and the record just wouldn't get updated
3) I debugged this in production yesterday, and when I went through it, it counted my vote correctly and the record got marked as approved
4) it worked totally fine locally, but that was also with other data
5) therefore I assume it's an error in the check whether it should be approved, but only for some conditions, which I haven't found yet

**Comment by MichaelKohler** [comment] 2019-07-31 20:18
Irvin mentioned that they were reviewing at a meetup, and also that they used a script to pre-select the thumbs-up button. I've looked at one instance where it didn't apply the approved flag and found this:

```
"lili668668"  1554474735    Friday, April 5, 2019 2:32:15 PM
"Allen"       1553047379    Wednesday, March 20, 2019 2:02:59 AM
"irvin",      1556887501    Friday, May 3, 2019 12:45:01 PM
"tingchia",   1556887886    Friday, May 3, 2019 12:51:26 PM
"ballfish",   1556888274    Friday, May 3, 2019 12:57:54 PM
"irvin1",     1559305258    Friday, May 31, 2019 12:20:58 PM
"irvin2",     1559305893    Friday, May 31, 2019 12:31:33 PM
"ballfish1",  1561861981    Sunday, June 30, 2019 2:33:01 AM
"Lily",       1563151085    Monday, July 15, 2019 12:38:05 AM
```

If everything was in the same time, I could totally see how it would not have been approved. Currently, if somebody has an old record locally and approves, it might overwrite the approval. I heavily doubt though that all instances had old records - these would need to be at least from March 20 or older. So I don't think this is the issue at hand.

**Comment by MichaelKohler** [comment] 2019-07-31 20:20
@nukeador could you live with the fact that the export could easily take 15-20 minutes? (of course depending on network and CPU and you know it..)

If so, I'd suggest to disregard the approval flag and calculate the approval for every sentence when exporting. This way we can circumvent whatever bug this is. Of course this would get slower and slower with more sentences added, though that's already the case anyway. Once we have a real backend, we can improve that massively.

**Comment by nukeador** [comment] 2019-07-31 20:43
I don't really like adding more complications to the export process. What are the alternatives?

Can't we just calculate and mark as validated these sentences as a one-off for zh-TW?

**Comment by MichaelKohler** [comment] 2019-07-31 20:46
> I don't really like adding more complications to the export process. What are the alternatives?

There are currently none that I see and the chances of me reproducing/debugging this issue is close to 0 by now.

> Can't we just calculate and mark as validated these sentences as a one-off for zh-TW?

Sure, we can. This doesn't fix anything for the future though.

**Comment by MichaelKohler** [comment] 2019-07-31 20:47
> Sure, we can. This doesn't fix anything for the future though.

And also potentially happening for other languages..

**Comment by irvin** [comment] 2019-08-01 03:36
So how to prevent it for the future, should we avoid all people meet, open the tool at the same time?

**Comment by irvin** [comment] 2019-08-01 03:38
> @nukeador could you live with the fact that the export could easily take 15-20 minutes? (of course depending on network and CPU and you know it..)

for an monthly export procedure 30 mins looks pretty fast to me, in compare to the sentences numbers we may recovered from the bug

**Comment by MichaelKohler** [comment] 2019-08-01 05:22
@irvin I can say that opening at the same time can lead to issues, yes. However, this doesn't seem to be the root cause of the issue here. So there is another bug somewhere...

**Comment by irvin** [comment] 2019-08-02 04:13
Sounds like "disregard the approval flag and calculate the approval numbers for every sentence when exporting" is a much easy and faster way to solve all unknown flag problem once and forever?

@nukeador don't you think it's actually simplified the process (don't check when approving on client side, avoid of dealing all async problems), but not "adding more complications"?

**Comment by nukeador** [comment] 2019-08-02 11:48
This seems like a technical decision, so up to @MichaelKohler to make the final decision here based on the impact on performance.

**Comment by MichaelKohler** [comment] 2019-08-03 17:56
The penalty we’re getting here is about 15-20 minutes of export instead of around 10-15. But of course, this heavily depends on the network connection and reliability as well as the processing power available. Since this is a technical decision, I’ll go with this approach. I will leave the issue here open to see if somebody can figure out why not all sentences get approved anymore.

Here’s the difference of exported sentences. The first number is checking the approval flag. The second number is checking every sentence according to the approvals, no matter if the approved flag is set.

Important note, we recently changed the algorithm to already set the “approved” flag if there are 2 votes and both are approvals, as the third vote won’t change anything. Records that have been reviewed twice before that change was made and haven’t been changed since the change has been made, didn’t have the “approved” flag set (by design). These of course are now also included in the export, though for those it heavily depends on the last-modified date whether these were just before the change or were actually hit by the bug we discuss here. In any case, this is an improvement as well!

As far as I’ve seen most of these differences come from the above fact, not the bug we have here. I’ve only seen the bug for zh-TW.

And then finally, also note that these might include sentences that got approved between my two export runs (negligable..).

cs: 2485 vs 3018
da: 266 vs 318
dv: 7000 vs 7011
en: 18607 vs 43487
ja: 4029 vs 4255
lv: 3488 vs 6232
nl. 23 vs 39
pl: 400 vs 505
rm-sursilv: 2367 vs 2588
rw: 2308 vs 2951
sah: 5230 vs 5846
sv: 5213 vs 5286
tt: 0 vs 296
zh-TW: 1179 vs 4420

I have created a diff and tested many (but not all!) sentences from that diff, to make sure that the new code works correctly and only approved sentences are exported. I haven’t found any bug, so I created a PR (https://github.com/Common-Voice/sentence-collector/pull/249). I also created a new export and created a PR in voice-web (https://github.com/mozilla/voice-web/pull/2145/files) with it, so that the additional sentences are available (which is quite some number!).

Something that just came to my mind: please note that for reviews we also filter on the approved flag, and therefore will most certainly show already approved sentences for review. What gets worse is that we sort the sentences for review depending on how close they are to be fully reviewed, so most of the sentences in the queue will be already approved but might lack the approval flag. This is bad. I will see if I can additionally write a script to rectify this issue. We can run this daily in a Travis CI pipeline, however I’d still prefer to find the initial source of this issue (which I’d say is hard). Note that until then, the “validated” and “unreviewed” metrics on the Sentence Collector dashboard won’t actually tell the truth as we filter for “approved” there as well.

I am aware that running this script regularly would mean that we probably couldn’t find the cause of this issue at hand, as it would get harder to spot. I’d rather have the review queue fixed..

@nukeador do you have thoughts for this?

@irvin can you tell the zh-TW contributors to start reviewing from the back (or somewhere in the middle) for now? Until I’ve written the script to set the approval flag for all currently approved sentences, that would make sure reviewers don’t spend time on already approved sentences.

**Comment by irvin** [comment] 2019-08-03 18:28
@MichaelKohler no problem, we most do that on Friday meetup after each time I add sentences, so I will make sure people are do it from back.

**Comment by lili668668** [comment] 2019-08-04 14:58
Hi,

I am the author of that tool. I am very sorry to make this bug. I want to say what I do in this tool.

That is a python script which is to send data to `/batch`.

I randomly took a request as a template. I thought that verifying a total of serveral people approved is implemented on the backend. At that time, I didn't know the code of the frontend. Thus, I missed a flag. I am sorry.

That script has another bug. I didn't notice that that timestamp is millisecond and number. The script send timestamp is second and string. That is another mistake. It's my fault. I am sorry.

**Comment by MichaelKohler** [comment] 2019-08-04 15:16
@lili668668 thanks for the explanation, I think this explains the issue at hand perfectly then. Note that with your script you also circumvent any validation that is done on the client. That's not a bad thing per se, as long as the review is done correctly.

And yes, I'm fully aware that we're currently doing too much on the client side. I'll come up with a proposal soon.

**Comment by MichaelKohler** [comment] 2019-08-04 15:16
Also, in that case I'm closing this here as we've found the issue.

**Closed by MichaelKohler** 2019-08-04 15:16 UTC
Labels: P1, area: review, bug

**Comment by MichaelKohler** [comment] 2019-08-04 16:14
an last but not least: I've corrected all wrongly flagged sentences, these should now all have the correct approval state. @irvin This also means that the review queue should now be correctly functioning as well (to be more exact: there are no more sentences to review right now).
